### ISSUE TITLE
Missing local modules

### ISSUE THREAD

**Issue by ascott1** [cfpb/student-debt-calculator#7]
@mistergone in the code there is reference to `./lib/enforce-range.js` and `./lib/calc-debt.js`, but these do not exist here or in your fork. Do you have these locally or have they not yet been written?

**Comment by mistergone** [comment]
Likely I forgot to `git add` them. I'll get them up there this afternoon.

**Comment by ascott1** [comment]
![THANK YOU](http://i.giphy.com/mPIA4KZVXv0ty.gif)

Thanks @mistergone!

**Comment by mistergone** [comment]
Fixed in https://github.com/mistergone/student-debt-calc/commit/149e3762dbfff8c98d6e0c16f64878c3fac7c7b5!
